name: flutter_qq_bridge
description: support QQ { login, getUserInfo, share news type }.
version: 0.0.1
author: neverwoods<zhanglulin1990@gmail.com>
homepage: https://github.com/neverwoodsS

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.zll.qq.flutterqqbridge
    pluginClass: FlutterQqBridgePlugin

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ">=0.1.4 <2.0.0"
